chore: use variableForUser
DevCycleHQ/ruby-server-sdk pull request #49
Opened 2023-03-13 13:32 UTC by nsalamad

2023-03-13 14:33 UTC, JamieSinn requested changes
Lets get the test harness enabled for this PR.

2023-03-13 14:39 UTC, nsalamad commented
> Lets get the test harness enabled for this PR.

Good call! I did run it locally and everything passed

2023-03-15 18:01 UTC, JamieSinn commented on lib/devcycle-ruby-server-sdk/localbucketing/local_bucketing.rb
> +      return nil if address == 0
we should log this too.

2023-03-15 18:01 UTC, JamieSinn approved these changes

2023-03-15 18:17 UTC, merged